const swearWords = [
    { word: "Pasan", origin: "Sri Lanka", meaning: "Karima ballek;Vanacharayek", example: "Pasan ube ammatahukpn." },
    { word: "Arse", origin: "UK – Old English", meaning: "Buttocks; insult meaning idiot", example: "Get off your arse and help me." },
    { word: "Arsehole", origin: "UK", meaning: "Anus; obnoxious person", example: "Stop being such an arsehole." },
    { word: "Ass", origin: "US", meaning: "Buttocks; fool", example: "Don’t make an ass of yourself." },
    { word: "Asshat", origin: "US", meaning: "Stupid or contemptible person", example: "Nice going, you absolute asshat." },
    { word: "Bastard", origin: "Middle English", meaning: "Originally illegitimate child; unpleasant person", example: "That cheating bastard!" },
    { word: "Bitch", origin: "Old English", meaning: "Female dog; derogatory term for woman", example: "She’s acting like a total bitch today." },
    { word: "Bollocks", origin: "UK", meaning: "Nonsense; also testicles", example: "That’s complete bollocks." },
    { word: "Bugger", origin: "UK/AUS", meaning: "To sodomize; mild insult", example: "Bugger off, will you?" },
    { word: "Bullshit", origin: "US", meaning: "Lies or nonsense", example: "That excuse is pure bullshit." },
    { word: "Choad", origin: "US", meaning: "Short, fat penis; idiot", example: "Quit being such a choad." },
    { word: "Cock", origin: "UK", meaning: "Penis; also term of endearment in UK", example: "He’s a right cocky bloke." },
    { word: "Cock-up", origin: "UK", meaning: "Mistake or failure", example: "Well, that was a right cock-up." },
    { word: "Crap", origin: "Middle English", meaning: "Feces; poor quality", example: "This phone is crap." },
    { word: "Cunt", origin: "UK/AUS", meaning: "Vulva; highly offensive insult", example: "He’s a nasty cunt." },
    { word: "Damn", origin: "Latin", meaning: "Curse invoking damnation", example: "Damn, that’s hot." },
    { word: "Dick", origin: "US", meaning: "Penis; insult for jerk", example: "Don’t be a dick." },
    { word: "Dipshit", origin: "US", meaning: "Stupid person", example: "Some dipshit parked in my spot." },
    { word: "Douchebag", origin: "US", meaning: "Contemptible person", example: "He’s such a douchebag." },
    { word: "Fuck", origin: "Germanic", meaning: "Sexual act; exclamation of anger", example: "What the fuck?" },
    { word: "Fucker", origin: "English", meaning: "Person who fucks; insult", example: "Lucky fucker, won the lottery." },
    { word: "Fuckhead", origin: "English", meaning: "Stupid or obnoxious person", example: "Listen, fuckhead…" },
    { word: "Fuckwit", origin: "UK/AUS", meaning: "Idiot", example: "He’s a complete fuckwit." },
    { word: "Goddamn", origin: "US", meaning: "Intensifier; mild blasphemy", example: "Goddamn it!" },
    { word: "Git", origin: "UK", meaning: "Annoying person", example: "You daft git!" },
    { word: "Hell", origin: "Biblical", meaning: "Place of punishment; exclamation", example: "What the hell is that?" },
    { word: "Ho", origin: "US slang", meaning: "Prostitute", example: "He’s always chasing hos." },
    { word: "Jackass", origin: "US", meaning: "Stupid or stubborn person", example: "Don’t be a jackass." },
    { word: "Jerk", origin: "US", meaning: "Rude or obnoxious person", example: "That jerk cut me off." },
    { word: "Motherfucker", origin: "English", meaning: "Insult; sometimes admiring", example: "That motherfucker can play guitar." },
    { word: "Muppet", origin: "UK", meaning: "Idiot; mildly insulting", example: "You absolute muppet." },
    { word: "Piss", origin: "Middle English", meaning: "Urine; to annoy (piss off)", example: "Don’t piss me off." },
    { word: "Prick", origin: "Middle English", meaning: "Penis; unpleasant person", example: "He’s being a prick again." },
    { word: "Pussy", origin: "English", meaning: "Vulva; coward", example: "Don’t be a pussy." },
    { word: "Shag", origin: "UK", meaning: "Sexual intercourse", example: "They had a quick shag." },
    { word: "Shit", origin: "Old English", meaning: "Feces; exclamation", example: "Oh shit!" },
    { word: "Shithead", origin: "US", meaning: "Stupid or contemptible person", example: "Some shithead keyed my car." },
    { word: "Slag", origin: "UK", meaning: "Promiscuous woman; insult", example: "She’s such a slag." },
    { word: "Slut", origin: "Middle English", meaning: "Promiscuous woman", example: "They called her a slut." },
    { word: "Son of a bitch", origin: "US", meaning: "Insult; mild in US", example: "You son of a bitch!" },
    { word: "Tits", origin: "English", meaning: "Breasts; mild annoyance", example: "Nice tits." },
    { word: "Tosser", origin: "UK", meaning: "Masturbator; idiot", example: "You bloody tosser." },
    { word: "Twat", origin: "UK", meaning: "Vulva; insult", example: "Don’t be such a twat." },
    { word: "Wanker", origin: "UK/AUS", meaning: "Masturbator; general insult", example: "Stupid wanker." },
    { word: "Whore", origin: "English", meaning: "Sex worker; derogatory for promiscuous woman", example: "She’s no whore." },
    { word: "Wuss", origin: "US", meaning: "Weak or cowardly person", example: "Stop being a wuss." },
    { word: "Yob", origin: "UK", meaning: "Rowdy or uncultured young man", example: "A gang of yobs." },
    { word: "Merda", origin: "Italian/Portuguese", meaning: "Shit", example: "Che merda!" },
    { word: "Putain", origin: "French", meaning: "Whore; common exclamation", example: "Putain, c’est fou!" },
    { word: "Schmuck", origin: "Yiddish/US", meaning: "Idiot; literally penis", example: "Don’t be a schmuck." },
    { word: "Pendejo", origin: "Spanish", meaning: "Coward/idiot; literally pubic hair", example: "Ese pendejo no sabe nada." }
];
